export const DEFAULT_VERSES = [
  { text: 'Peace I leave with you; my peace I give you. I do not give to you as the world gives.', reference: 'John 14:27' },
  { text: 'For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you.', reference: 'Jeremiah 29:11' },
  { text: 'The Lord is my shepherd; I shall not want.', reference: 'Psalm 23:1' },
  { text: 'I can do all things through Christ who strengthens me.', reference: 'Philippians 4:13' },
  { text: 'Trust in the Lord with all your heart and lean not on your own understanding.', reference: 'Proverbs 3:5' },
  { text: 'Be strong and courageous. Do not be afraid; do not be discouraged.', reference: 'Joshua 1:9' },
  { text: 'The Lord is my light and my salvation — whom shall I fear?', reference: 'Psalm 27:1' },
  { text: 'Come to me, all you who are weary and burdened, and I will give you rest.', reference: 'Matthew 11:28' },
  { text: 'And we know that in all things God works for the good of those who love him.', reference: 'Romans 8:28' },
  { text: 'I am the way and the truth and the life.', reference: 'John 14:6' },
  { text: 'The Lord is close to the brokenhearted and saves those who are crushed in spirit.', reference: 'Psalm 34:18' },
  { text: 'But those who hope in the Lord will renew their strength.', reference: 'Isaiah 40:31' },
  { text: 'Do not be anxious about anything, but in every situation, by prayer and petition, present your requests to God.', reference: 'Philippians 4:6' },
  { text: 'For God so loved the world that he gave his one and only Son.', reference: 'John 3:16' },
  { text: 'The Lord bless you and keep you; the Lord make his face shine on you.', reference: 'Numbers 6:24-25' },
  { text: 'Your word is a lamp for my feet, a light on my path.', reference: 'Psalm 119:105' },
  { text: 'Cast all your anxiety on him because he cares for you.', reference: '1 Peter 5:7' },
  { text: 'Be still, and know that I am God.', reference: 'Psalm 46:10' },
  { text: 'The Lord is gracious and compassionate, slow to anger and rich in love.', reference: 'Psalm 145:8' },
  { text: 'Blessed are the pure in heart, for they will see God.', reference: 'Matthew 5:8' },
  { text: 'Delight yourself in the Lord, and he will give you the desires of your heart.', reference: 'Psalm 37:4' },
  { text: 'God is our refuge and strength, an ever-present help in trouble.', reference: 'Psalm 46:1' },
  { text: 'For where two or three gather in my name, there am I with them.', reference: 'Matthew 18:20' },
  { text: 'The fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.', reference: 'Galatians 5:22' },
  { text: 'Ask and it will be given to you; seek and you will find; knock and the door will be opened.', reference: 'Matthew 7:7' },
  { text: 'He heals the brokenhearted and binds up their wounds.', reference: 'Psalm 147:3' },
  { text: 'I have told you these things, so that in me you may have peace.', reference: 'John 16:33' },
  { text: 'The Lord your God is with you, the Mighty Warrior who saves.', reference: 'Zephaniah 3:17' },
  { text: 'Therefore, if anyone is in Christ, the new creation has come.', reference: '2 Corinthians 5:17' },
  { text: 'Love is patient, love is kind. It does not envy, it does not boast.', reference: '1 Corinthians 13:4' },
  { text: 'Commit your way to the Lord; trust in him and he will do this.', reference: 'Psalm 37:5' },
  { text: 'My grace is sufficient for you, for my power is made perfect in weakness.', reference: '2 Corinthians 12:9' },
  { text: 'The name of the Lord is a fortified tower; the righteous run to it and are safe.', reference: 'Proverbs 18:10' },
  { text: 'Blessed is the one who trusts in the Lord, whose confidence is in him.', reference: 'Jeremiah 17:7' },
  { text: 'Have I not commanded you? Be strong and courageous.', reference: 'Joshua 1:9' },
  { text: 'In their hearts humans plan their course, but the Lord establishes their steps.', reference: 'Proverbs 16:9' },
  { text: 'The Lord is my rock, my fortress and my deliverer.', reference: 'Psalm 18:2' },
  { text: 'May the God of hope fill you with all joy and peace as you trust in him.', reference: 'Romans 15:13' },
  { text: 'Create in me a pure heart, O God, and renew a steadfast spirit within me.', reference: 'Psalm 51:10' },
  { text: 'No weapon formed against you shall prosper.', reference: 'Isaiah 54:17' },
  { text: 'I sought the Lord, and he answered me; he delivered me from all my fears.', reference: 'Psalm 34:4' },
  { text: 'But seek first his kingdom and his righteousness, and all these things will be given to you.', reference: 'Matthew 6:33' },
  { text: 'The steadfast love of the Lord never ceases; his mercies never come to an end.', reference: 'Lamentations 3:22' },
  { text: 'For nothing will be impossible with God.', reference: 'Luke 1:37' },
  { text: 'He who began a good work in you will carry it on to completion.', reference: 'Philippians 1:6' },
  { text: 'Draw near to God, and he will draw near to you.', reference: 'James 4:8' },
  { text: 'Wait for the Lord; be strong and take heart and wait for the Lord.', reference: 'Psalm 27:14' },
  { text: 'Every good and perfect gift is from above, coming down from the Father of lights.', reference: 'James 1:17' },
  { text: 'Hail Mary, full of grace, the Lord is with thee. Blessed art thou among women.', reference: 'Luke 1:28' },
  { text: 'My soul magnifies the Lord, and my spirit rejoices in God my Savior.', reference: 'Luke 1:46-47' },
];
